### ISSUE TITLE
dataloader for EPIC kitchen

### ISSUE THREAD

**Issue by ClaraBing** [fabienbaradel/object_level_visual_reasoning#1]
Hi Fabien,

Thanks so much for putting up the code! May I ask if you could also provide the loader file for EPIC kitchen please?

**Comment by fabienbaradel** [comment]
Hi @ClaraBing thanks for interest in our work, I hope it helps in your research.
I plan to add the dataloader for EPIC Kitchen in few weeks. I recommend the [official EPIC Kitchen dataloader](https://github.com/epic-kitchens/starter-kit-action-recognition) for training/testing your model.
There is an [official python library](https://github.com/epic-kitchens/epic-lib) which has been released recently by the EPIC Kitchen team: `pip install epic-kitchens`

**Comment by ClaraBing** [comment]
Sounds good, thank you so much Fabien!
