### ISSUE TITLE
Demo on own video

### ISSUE THREAD

**Issue by sophia-wright-blue** [fabienbaradel/object_level_visual_reasoning#3]
Thank you for releasing this repo. Would it be possible to use this model to do a demo on my own video? What would the steps to do so be?

Thanks,

**Comment by fabienbaradel** [comment]
Hi @sophia-wright-blue,
Thanks for your interest in our work. For sure you can run the code on your own video. The only one prerequisite is to first detect objects with mask-RCNN. One video should have an associated masks file.
Once you have the detected objects and their masks it is straightforward using the `validate`function (cf below): https://github.com/fabienbaradel/object_level_visual_reasoning/blob/f504715c2ea9464e8dd4076584c30ab34937de22/inference/train_val.py#L148

**Comment by sophia-wright-blue** [comment]
thank you for the detailed reply @fabienbaradel , i'm gonna give that a shot, i look forward to understanding your model better, my eventual objective is to produce output similar to FIg 5 in your paper ("Object Level Visual Reasoning in Videos"), but with complete <human, verb, object> classification. Thanks again,
